
var ortWasm = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(ortWasm = {})  {

var c;c||(c=typeof ortWasm !== 'undefined' ? ortWasm : {});var aa,k;c.ready=new Promise((a,b)=>{aa=a;k=b});"use strict";c.jsepInit=function(a,b,d,f,g,h,l,n){c.Ta=a;c.Fa=b;c.Ha=d;c.Da=f;c.Ga=g;c.na=h;c.Ia=l;c.Ja=n};var ba=Object.assign({},c),u="./this.program",x=(a,b)=>{throw b;},ca="object"==typeof window,y="function"==typeof importScripts,z="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,A="",B,C,D;
if(z){var fs=require("fs"),E=require("path");A=y?E.dirname(A)+"/":__dirname+"/";B=(a,b)=>{a=a.startsWith("file://")?new URL(a):E.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};D=a=>{a=B(a,!0);a.buffer||(a=new Uint8Array(a));return a};C=(a,b,d,f=!0)=>{a=a.startsWith("file://")?new URL(a):E.normalize(a);fs.readFile(a,f?void 0:"utf8",(g,h)=>{g?d(g):b(f?h.buffer:h)})};!c.thisProgram&&1<process.argv.length&&(u=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);x=(a,b)=>{process.exitCode=
a;throw b;};c.inspect=()=>"[Emscripten Module object]"}else if(ca||y)y?A=self.location.href:"undefined"!=typeof document&&document.currentScript&&(A=document.currentScript.src),_scriptDir&&(A=_scriptDir),0!==A.indexOf("blob:")?A=A.substr(0,A.replace(/[?#].*/,"").lastIndexOf("/")+1):A="",B=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},y&&(D=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
C=(a,b,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?b(f.response):d()};f.onerror=d;f.send(null)};var da=c.print||console.log.bind(console),G=c.printErr||console.warn.bind(console);Object.assign(c,ba);ba=null;c.thisProgram&&(u=c.thisProgram);c.quit&&(x=c.quit);var H;c.wasmBinary&&(H=c.wasmBinary);var noExitRuntime=c.noExitRuntime||!0;"object"!=typeof WebAssembly&&I("no native wasm support detected");
var J,K=!1,L,M,N,O,P,ea;function fa(){var a=J.buffer;c.HEAP8=M=new Int8Array(a);c.HEAP16=new Int16Array(a);c.HEAP32=O=new Int32Array(a);c.HEAPU8=N=new Uint8Array(a);c.HEAPU16=new Uint16Array(a);c.HEAPU32=P=new Uint32Array(a);c.HEAPF32=new Float32Array(a);c.HEAPF64=ea=new Float64Array(a)}var ha=[],ia=[],ja=[];function ka(){var a=c.preRun.shift();ha.unshift(a)}var Q=0,R=null,S=null;
function I(a){if(c.onAbort)c.onAbort(a);a="Aborted("+a+")";G(a);K=!0;L=1;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");k(a);throw a;}function la(a){return a.startsWith("data:application/octet-stream;base64,")}var T;T="ort-wasm-simd.wasm";if(!la(T)){var ma=T;T=c.locateFile?c.locateFile(ma,A):A+ma}function na(a){try{if(a==T&&H)return new Uint8Array(H);if(D)return D(a);throw"both async and sync fetching of the wasm failed";}catch(b){I(b)}}
function oa(a){if(!H&&(ca||y)){if("function"==typeof fetch&&!a.startsWith("file://"))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>na(a));if(C)return new Promise((b,d)=>{C(a,f=>b(new Uint8Array(f)),d)})}return Promise.resolve().then(()=>na(a))}function pa(a,b,d){return oa(a).then(f=>WebAssembly.instantiate(f,b)).then(f=>f).then(d,f=>{G("failed to asynchronously prepare wasm: "+f);I(f)})}
function qa(a,b){var d=T;return H||"function"!=typeof WebAssembly.instantiateStreaming||la(d)||d.startsWith("file://")||z||"function"!=typeof fetch?pa(d,a,b):fetch(d,{credentials:"same-origin"}).then(f=>WebAssembly.instantiateStreaming(f,a).then(b,function(g){G("wasm streaming compile failed: "+g);G("falling back to ArrayBuffer instantiation");return pa(d,a,b)}))}
var ra={883856:()=>{c.jsepRunPromise=new Promise(function(a){c.Ka=a})},883951:a=>{c.Ka(a)},883989:a=>c.Fa(a),884022:a=>c.Ha(a),884054:(a,b,d)=>{c.Da(a,b,d,!0)},884093:(a,b,d)=>{c.Da(a,b,d)},884126:a=>{c.na("Abs",a,void 0)},884177:a=>{c.na("Neg",a,void 0)},884228:a=>{c.na("Floor",a,void 0)},884281:a=>{c.na("Ceil",a,void 0)},884333:a=>{c.na("Reciprocal",a,void 0)},884391:a=>{c.na("Sqrt",a,void 0)},884443:a=>{c.na("Exp",a,void 0)},884494:a=>{c.na("Erf",a,void 0)},884545:a=>{c.na("Sigmoid",a,void 0)},
884600:a=>{c.na("Sin",a,void 0)},884651:a=>{c.na("Cos",a,void 0)},884702:a=>{c.na("Tan",a,void 0)},884753:a=>{c.na("Asin",a,void 0)},884805:a=>{c.na("Acos",a,void 0)},884857:a=>{c.na("Atan",a,void 0)},884909:a=>{c.na("Sinh",a,void 0)},884961:a=>{c.na("Cosh",a,void 0)},885013:a=>{c.na("Asinh",a,void 0)},885066:a=>{c.na("Acosh",a,void 0)},885119:a=>{c.na("Atanh",a,void 0)},885172:(a,b,d)=>{c.na("ClipV10",a,{min:b,max:d})},885244:a=>{c.na("Clip",a,void 0)},885296:(a,b)=>{c.na("Elu",a,{alpha:b})},885354:a=>
{c.na("Relu",a,void 0)},885406:(a,b)=>{c.na("LeakyRelu",a,{alpha:b})},885470:(a,b)=>{c.na("ThresholdedRelu",a,{alpha:b})},885540:a=>{c.na("Add",a,void 0)},885591:a=>{c.na("Sub",a,void 0)},885642:a=>{c.na("Mul",a,void 0)},885693:a=>{c.na("Div",a,void 0)},885744:a=>{c.na("Pow",a,void 0)},885795:(a,b,d)=>{c.na("Transpose",a,{perm:b?Array.from(O.subarray(d>>>0,d+b>>>0)):[]})},885908:(a,b,d,f,g,h,l,n,r,q)=>{c.na("Conv",a,{format:r?"NHWC":"NCHW",auto_pad:b,dilations:[d],group:f,kernel_shape:[g],pads:[h,
l],strides:[n],w_is_const:()=>!!M[q>>>0]})},886136:(a,b,d,f,g,h,l,n,r,q,t,v,w,e,m)=>{c.na("Conv",a,{format:e?"NHWC":"NCHW",auto_pad:b,dilations:[d,f],group:g,kernel_shape:[h,l],pads:[n,r,q,t],strides:[v,w],w_is_const:()=>!!M[m>>>0]})},886395:(a,b,d,f,g,h,l,n,r,q)=>{c.na("Conv",a,{format:r?"NHWC":"NCHW",auto_pad:b,dilations:[d],group:f,kernel_shape:[g],pads:[h,l],strides:[n],w_is_const:()=>!!M[q>>>0]})},886623:(a,b,d,f,g,h,l,n,r,q,t,v,w,e,m)=>{c.na("Conv",a,{format:e?"NHWC":"NCHW",auto_pad:b,dilations:[d,
f],group:g,kernel_shape:[h,l],pads:[n,r,q,t],strides:[v,w],w_is_const:()=>!!M[m>>>0]})},886882:(a,b)=>{c.na("GlobalAveragePool",a,{format:b?"NHWC":"NCHW"})},886973:(a,b,d,f,g,h,l,n,r,q,t,v,w,e,m,p)=>{c.na("AveragePool",a,{format:p?"NHWC":"NCHW",auto_pad:b,ceil_mode:d,count_include_pad:f,storage_order:g,dilations:[h,l],kernel_shape:[n,r],pads:[q,t,v,w],strides:[e,m]})},887257:(a,b)=>{c.na("GlobalAveragePool",a,{format:b?"NHWC":"NCHW"})},887348:(a,b,d,f,g,h,l,n,r,q,t,v,w,e,m,p)=>{c.na("AveragePool",
a,{format:p?"NHWC":"NCHW",auto_pad:b,ceil_mode:d,count_include_pad:f,storage_order:g,dilations:[h,l],kernel_shape:[n,r],pads:[q,t,v,w],strides:[e,m]})},887632:(a,b)=>{c.na("GlobalMaxPool",a,{format:b?"NHWC":"NCHW"})},887719:(a,b,d,f,g,h,l,n,r,q,t,v,w,e,m,p)=>{c.na("MaxPool",a,{format:p?"NHWC":"NCHW",auto_pad:b,ceil_mode:d,count_include_pad:f,storage_order:g,dilations:[h,l],kernel_shape:[n,r],pads:[q,t,v,w],strides:[e,m]})},887999:(a,b)=>{c.na("GlobalMaxPool",a,{format:b?"NHWC":"NCHW"})},888086:(a,
b,d,f,g,h,l,n,r,q,t,v,w,e,m,p)=>{c.na("MaxPool",a,{format:p?"NHWC":"NCHW",auto_pad:b,ceil_mode:d,count_include_pad:f,storage_order:g,dilations:[h,l],kernel_shape:[n,r],pads:[q,t,v,w],strides:[e,m]})},888366:(a,b,d,f,g)=>{c.na("Gemm",a,{alpha:b,beta:d,transA:f,transB:g})},888470:a=>{c.na("MatMul",a,void 0)},888524:a=>{c.Ia(a)},888558:(a,b)=>c.Ja(a,b)};function sa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}
function ta(a){for(;0<a.length;)a.shift()(c)}function ua(a){this.Ba=a-24;this.Sa=function(b){P[this.Ba+4>>2>>>0]=b};this.Ra=function(b){P[this.Ba+8>>2>>>0]=b};this.La=function(b,d){this.Qa();this.Sa(b);this.Ra(d)};this.Qa=function(){P[this.Ba+16>>2>>>0]=0}}var va=0,wa=0,xa="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ya(a,b,d){b>>>=0;var f=b+d;for(d=b;a[d]&&!(d>=f);)++d;if(16<d-b&&a.buffer&&xa)return xa.decode(a.subarray(b,d));for(f="";b<d;){var g=a[b++];if(g&128){var h=a[b++]&63;if(192==(g&224))f+=String.fromCharCode((g&31)<<6|h);else{var l=a[b++]&63;g=224==(g&240)?(g&15)<<12|h<<6|l:(g&7)<<18|h<<12|l<<6|a[b++]&63;65536>g?f+=String.fromCharCode(g):(g-=65536,f+=String.fromCharCode(55296|g>>10,56320|g&1023))}}else f+=String.fromCharCode(g)}return f}function za(a,b){return(a>>>=0)?ya(N,a,b):""}
function Aa(a){for(var b=0,d=0;d<a.length;++d){var f=a.charCodeAt(d);127>=f?b++:2047>=f?b+=2:55296<=f&&57343>=f?(b+=4,++d):b+=3}return b}
function Ba(a,b,d,f){d>>>=0;if(!(0<f))return 0;var g=d;f=d+f-1;for(var h=0;h<a.length;++h){var l=a.charCodeAt(h);if(55296<=l&&57343>=l){var n=a.charCodeAt(++h);l=65536+((l&1023)<<10)|n&1023}if(127>=l){if(d>=f)break;b[d++>>>0]=l}else{if(2047>=l){if(d+1>=f)break;b[d++>>>0]=192|l>>6}else{if(65535>=l){if(d+2>=f)break;b[d++>>>0]=224|l>>12}else{if(d+3>=f)break;b[d++>>>0]=240|l>>18;b[d++>>>0]=128|l>>12&63}b[d++>>>0]=128|l>>6&63}b[d++>>>0]=128|l&63}}b[d>>>0]=0;return d-g}
function Ca(a,b,d){return Ba(a,N,b,d)}function U(a){return 0===a%4&&(0!==a%100||0===a%400)}var Da=[0,31,60,91,121,152,182,213,244,274,305,335],Ea=[0,31,59,90,120,151,181,212,243,273,304,334];function Fa(a){return(U(a.getFullYear())?Da:Ea)[a.getMonth()]+a.getDate()-1}function Ga(a){var b=Aa(a)+1,d=Ha(b);d&&Ca(a,d,b);return d}var Ia=[];function Ka(a,b,d){Ia.length=0;var f;for(d>>=2;f=N[b++>>>0];)d+=105!=f&d,Ia.push(105==f?O[d>>>0]:ea[d++>>>1]),++d;return ra[a].apply(null,Ia)}var La={};
function Ma(){if(!Na){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:u||"./this.program"},b;for(b in La)void 0===La[b]?delete a[b]:a[b]=La[b];var d=[];for(b in a)d.push(b+"="+a[b]);Na=d}return Na}var Na;function Oa(a){L=L=a;if(!noExitRuntime){if(c.onExit)c.onExit(a);K=!0}x(a,new sa(a))}var Pa=[null,[],[]];
function Qa(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return d=>crypto.getRandomValues(d);if(z)try{var a=require("crypto");if(a.randomFillSync)return d=>a.randomFillSync(d);var b=a.randomBytes;return d=>(d.set(b(d.byteLength)),d)}catch(d){}I("initRandomDevice")}function Ra(a){return(Ra=Qa())(a)}var Sa=[31,29,31,30,31,30,31,31,30,31,30,31],Ta=[31,28,31,30,31,30,31,31,30,31,30,31];function Ua(a){var b=Array(Aa(a)+1);Ba(a,b,0,b.length);return b}
function Va(a,b,d,f){function g(e,m,p){for(e="number"==typeof e?e.toString():e||"";e.length<m;)e=p[0]+e;return e}function h(e,m){return g(e,m,"0")}function l(e,m){function p(Ja){return 0>Ja?-1:0<Ja?1:0}var F;0===(F=p(e.getFullYear()-m.getFullYear()))&&0===(F=p(e.getMonth()-m.getMonth()))&&(F=p(e.getDate()-m.getDate()));return F}function n(e){switch(e.getDay()){case 0:return new Date(e.getFullYear()-1,11,29);case 1:return e;case 2:return new Date(e.getFullYear(),0,3);case 3:return new Date(e.getFullYear(),
0,2);case 4:return new Date(e.getFullYear(),0,1);case 5:return new Date(e.getFullYear()-1,11,31);case 6:return new Date(e.getFullYear()-1,11,30)}}function r(e){var m=e.wa;for(e=new Date((new Date(e.xa+1900,0,1)).getTime());0<m;){var p=e.getMonth(),F=(U(e.getFullYear())?Sa:Ta)[p];if(m>F-e.getDate())m-=F-e.getDate()+1,e.setDate(1),11>p?e.setMonth(p+1):(e.setMonth(0),e.setFullYear(e.getFullYear()+1));else{e.setDate(e.getDate()+m);break}}p=new Date(e.getFullYear()+1,0,4);m=n(new Date(e.getFullYear(),
0,4));p=n(p);return 0>=l(m,e)?0>=l(p,e)?e.getFullYear()+1:e.getFullYear():e.getFullYear()-1}var q=O[f+40>>2>>>0];f={Oa:O[f>>2>>>0],Na:O[f+4>>2>>>0],ya:O[f+8>>2>>>0],Ca:O[f+12>>2>>>0],za:O[f+16>>2>>>0],xa:O[f+20>>2>>>0],ra:O[f+24>>2>>>0],wa:O[f+28>>2>>>0],Ua:O[f+32>>2>>>0],Ma:O[f+36>>2>>>0],Pa:q?za(q):""};d=za(d);q={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y",
"%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var t in q)d=d.replace(new RegExp(t,"g"),q[t]);var v="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),w="January February March April May June July August September October November December".split(" ");q={"%a":function(e){return v[e.ra].substring(0,3)},"%A":function(e){return v[e.ra]},"%b":function(e){return w[e.za].substring(0,
3)},"%B":function(e){return w[e.za]},"%C":function(e){return h((e.xa+1900)/100|0,2)},"%d":function(e){return h(e.Ca,2)},"%e":function(e){return g(e.Ca,2," ")},"%g":function(e){return r(e).toString().substring(2)},"%G":function(e){return r(e)},"%H":function(e){return h(e.ya,2)},"%I":function(e){e=e.ya;0==e?e=12:12<e&&(e-=12);return h(e,2)},"%j":function(e){for(var m=0,p=0;p<=e.za-1;m+=(U(e.xa+1900)?Sa:Ta)[p++]);return h(e.Ca+m,3)},"%m":function(e){return h(e.za+1,2)},"%M":function(e){return h(e.Na,
2)},"%n":function(){return"\n"},"%p":function(e){return 0<=e.ya&&12>e.ya?"AM":"PM"},"%S":function(e){return h(e.Oa,2)},"%t":function(){return"\t"},"%u":function(e){return e.ra||7},"%U":function(e){return h(Math.floor((e.wa+7-e.ra)/7),2)},"%V":function(e){var m=Math.floor((e.wa+7-(e.ra+6)%7)/7);2>=(e.ra+371-e.wa-2)%7&&m++;if(m)53==m&&(p=(e.ra+371-e.wa)%7,4==p||3==p&&U(e.xa)||(m=1));else{m=52;var p=(e.ra+7-e.wa-1)%7;(4==p||5==p&&U(e.xa%400-1))&&m++}return h(m,2)},"%w":function(e){return e.ra},"%W":function(e){return h(Math.floor((e.wa+
7-(e.ra+6)%7)/7),2)},"%y":function(e){return(e.xa+1900).toString().substring(2)},"%Y":function(e){return e.xa+1900},"%z":function(e){e=e.Ma;var m=0<=e;e=Math.abs(e)/60;return(m?"+":"-")+String("0000"+(e/60*100+e%60)).slice(-4)},"%Z":function(e){return e.Pa},"%%":function(){return"%"}};d=d.replace(/%%/g,"\x00\x00");for(t in q)d.includes(t)&&(d=d.replace(new RegExp(t,"g"),q[t](f)));d=d.replace(/\0\0/g,"%");t=Ua(d);if(t.length>b)return 0;M.set(t,a>>>0);return t.length-1}
function V(a){try{a()}catch(b){I(b)}}function Wa(a){a instanceof sa||"unwind"==a||x(1,a)}function Xa(a){var b={},d;for(d in a)(function(f){var g=a[f];b[f]="function"==typeof g?function(){W.push(f);try{return g.apply(null,arguments)}finally{K||(W.pop()===f||I(),X&&1===Y&&0===W.length&&(Y=0,V(Ya),"undefined"!=typeof Fibers&&Fibers.Va()))}}:g})(d);return b}var Y=0,X=null,Za=0,W=[],$a={},ab={},bb=0,cb=null,db=[];
function eb(){var a=Ha(65548),b=a+12;O[a>>2>>>0]=b;O[a+4>>2>>>0]=b+65536;b=W[0];var d=$a[b];void 0===d&&(d=bb++,$a[b]=d,ab[d]=b);O[a+8>>2>>>0]=d;return a}
function fb(a){if(!K){if(0===Y){var b=!1,d=!1;a((f=0)=>{if(!K&&(Za=f,b=!0,d)){Y=2;V(()=>gb(X));"undefined"!=typeof Browser&&Browser.Aa.Ea&&Browser.Aa.resume();f=!1;try{var g=(0,c.asm[ab[O[X+8>>2>>>0]]])()}catch(n){g=n,f=!0}var h=!1;if(!X){var l=cb;l&&(cb=null,(f?l.reject:l.resolve)(g),h=!0)}if(f&&!h)throw g;}});d=!0;b||(Y=1,X=eb(),"undefined"!=typeof Browser&&Browser.Aa.Ea&&Browser.Aa.pause(),V(()=>hb(X)))}else 2===Y?(Y=0,V(ib),jb(X),X=null,db.forEach(f=>{if(!K)try{if(f(),!noExitRuntime)try{Oa(L)}catch(g){Wa(g)}}catch(g){Wa(g)}})):
I("invalid state: "+Y);return Za}}function kb(a){return fb(b=>{a().then(b)})}
var lb={o:function(a,b,d){return kb(async()=>{await c.Ga(a,b,d)})},a:function(a,b,d){(new ua(a)).La(b,d);va=a;wa++;throw va;},m:function(){I("To use dlopen, you need enable dynamic linking, see https://emscripten.org/docs/compiling/Dynamic-Linking.html")},g:function(){return 0},M:function(){},x:function(){},z:function(){},O:function(){return 0},K:function(){},G:function(){},J:function(){},k:function(){},y:function(){},v:function(){},L:function(){},w:function(){},P:function(){return!0},D:function(a,
b){a=new Date(1E3*(P[a>>>2]+4294967296*O[a+4>>>2]));O[b>>2>>>0]=a.getUTCSeconds();O[b+4>>2>>>0]=a.getUTCMinutes();O[b+8>>2>>>0]=a.getUTCHours();O[b+12>>2>>>0]=a.getUTCDate();O[b+16>>2>>>0]=a.getUTCMonth();O[b+20>>2>>>0]=a.getUTCFullYear()-1900;O[b+24>>2>>>0]=a.getUTCDay();O[b+28>>2>>>0]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0},E:function(a,b){a=new Date(1E3*(P[a>>>2]+4294967296*O[a+4>>>2]));O[b>>2>>>0]=a.getSeconds();O[b+4>>2>>>0]=a.getMinutes();O[b+8>>2>>>0]=a.getHours();O[b+
12>>2>>>0]=a.getDate();O[b+16>>2>>>0]=a.getMonth();O[b+20>>2>>>0]=a.getFullYear()-1900;O[b+24>>2>>>0]=a.getDay();O[b+28>>2>>>0]=Fa(a)|0;O[b+36>>2>>>0]=-(60*a.getTimezoneOffset());var d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset(),f=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();O[b+32>>2>>>0]=(d!=f&&a.getTimezoneOffset()==Math.min(f,d))|0},F:function(a){var b=new Date(O[a+20>>2>>>0]+1900,O[a+16>>2>>>0],O[a+12>>2>>>0],O[a+8>>2>>>0],O[a+4>>2>>>0],O[a>>2>>>0],0),d=O[a+32>>2>>>0],f=b.getTimezoneOffset(),
g=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),h=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),l=Math.min(h,g);0>d?O[a+32>>2>>>0]=Number(g!=h&&l==f):0<d!=(l==f)&&(g=Math.max(h,g),b.setTime(b.getTime()+6E4*((0<d?l:g)-f)));O[a+24>>2>>>0]=b.getDay();O[a+28>>2>>>0]=Fa(b)|0;O[a>>2>>>0]=b.getSeconds();O[a+4>>2>>>0]=b.getMinutes();O[a+8>>2>>>0]=b.getHours();O[a+12>>2>>>0]=b.getDate();O[a+16>>2>>>0]=b.getMonth();O[a+20>>2>>>0]=b.getYear();return b.getTime()/1E3|0},A:function(){return-52},C:function(){},
t:function(a,b,d){function f(r){return(r=r.toTimeString().match(/\(([A-Za-z ]+)\)$/))?r[1]:"GMT"}var g=(new Date).getFullYear(),h=new Date(g,0,1),l=new Date(g,6,1);g=h.getTimezoneOffset();var n=l.getTimezoneOffset();P[a>>2>>>0]=60*Math.max(g,n);O[b>>2>>>0]=Number(g!=n);a=f(h);b=f(l);a=Ga(a);b=Ga(b);n<g?(P[d>>2>>>0]=a,P[d+4>>2>>>0]=b):(P[d>>2>>>0]=b,P[d+4>>2>>>0]=a)},e:function(){I("")},B:function(){I("To use dlopen, you need enable dynamic linking, see https://emscripten.org/docs/compiling/Dynamic-Linking.html")},
b:function(a,b,d){return Ka(a,b,d)},h:function(a,b,d){return Ka(a,b,d)},l:function(){return Date.now()},u:function(){return 4294901760},d:z?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now(),N:function(a,b,d){N.copyWithin(a>>>0,b>>>0,b+d>>>0)},s:function(a){var b=N.length;a>>>=0;if(4294901760<a)return!1;for(var d=1;4>=d;d*=2){var f=b*(1+.2/d);f=Math.min(f,a+100663296);var g=Math,h=g.min;f=Math.max(a,f);f+=(65536-f%65536)%65536;a:{var l=J.buffer;try{J.grow(h.call(g,4294901760,
f)-l.byteLength+65535>>>16);fa();var n=1;break a}catch(r){}n=void 0}if(n)return!0}return!1},H:function(a,b){var d=0;Ma().forEach(function(f,g){var h=b+d;g=P[a+4*g>>2>>>0]=h;for(h=0;h<f.length;++h)M[g++>>0>>>0]=f.charCodeAt(h);M[g>>0>>>0]=0;d+=f.length+1});return 0},I:function(a,b){var d=Ma();P[a>>2>>>0]=d.length;var f=0;d.forEach(function(g){f+=g.length+1});P[b>>2>>>0]=f;return 0},n:Oa,f:function(){return 52},j:function(){return 52},p:function(){return 70},i:function(a,b,d,f){for(var g=0,h=0;h<d;h++){var l=
P[b>>2>>>0],n=P[b+4>>2>>>0];b+=8;for(var r=0;r<n;r++){var q=N[l+r>>>0],t=Pa[a];0===q||10===q?((1===a?da:G)(ya(t,0)),t.length=0):t.push(q)}g+=n}P[f>>2>>>0]=g;return 0},q:function(a,b){Ra(N.subarray(a>>>0,a+b>>>0));return 0},r:Va,c:function(a,b,d,f){return Va(a,b,d,f)}};
(function(){function a(d){d=d.exports;d=Xa(d);c.asm=d;J=c.asm.Q;fa();ia.unshift(c.asm.R);Q--;c.monitorRunDependencies&&c.monitorRunDependencies(Q);if(0==Q&&(null!==R&&(clearInterval(R),R=null),S)){var f=S;S=null;f()}return d}var b={a:lb};Q++;c.monitorRunDependencies&&c.monitorRunDependencies(Q);if(c.instantiateWasm)try{return c.instantiateWasm(b,a)}catch(d){G("Module.instantiateWasm callback failed with error: "+d),k(d)}qa(b,function(d){a(d.instance)}).catch(k);return{}})();
c._OrtInit=function(){return(c._OrtInit=c.asm.S).apply(null,arguments)};c._OrtCreateSessionOptions=function(){return(c._OrtCreateSessionOptions=c.asm.T).apply(null,arguments)};c._OrtAppendExecutionProvider=function(){return(c._OrtAppendExecutionProvider=c.asm.U).apply(null,arguments)};c._OrtAddSessionConfigEntry=function(){return(c._OrtAddSessionConfigEntry=c.asm.V).apply(null,arguments)};c._OrtReleaseSessionOptions=function(){return(c._OrtReleaseSessionOptions=c.asm.W).apply(null,arguments)};
c._OrtCreateSession=function(){return(c._OrtCreateSession=c.asm.X).apply(null,arguments)};c._OrtReleaseSession=function(){return(c._OrtReleaseSession=c.asm.Y).apply(null,arguments)};c._OrtGetInputCount=function(){return(c._OrtGetInputCount=c.asm.Z).apply(null,arguments)};c._OrtGetOutputCount=function(){return(c._OrtGetOutputCount=c.asm._).apply(null,arguments)};c._OrtGetInputName=function(){return(c._OrtGetInputName=c.asm.$).apply(null,arguments)};
c._OrtGetOutputName=function(){return(c._OrtGetOutputName=c.asm.aa).apply(null,arguments)};c._OrtFree=function(){return(c._OrtFree=c.asm.ba).apply(null,arguments)};c._OrtCreateTensor=function(){return(c._OrtCreateTensor=c.asm.ca).apply(null,arguments)};c._OrtGetTensorData=function(){return(c._OrtGetTensorData=c.asm.da).apply(null,arguments)};c._OrtReleaseTensor=function(){return(c._OrtReleaseTensor=c.asm.ea).apply(null,arguments)};
c._OrtCreateRunOptions=function(){return(c._OrtCreateRunOptions=c.asm.fa).apply(null,arguments)};c._OrtAddRunConfigEntry=function(){return(c._OrtAddRunConfigEntry=c.asm.ga).apply(null,arguments)};c._OrtReleaseRunOptions=function(){return(c._OrtReleaseRunOptions=c.asm.ha).apply(null,arguments)};c._OrtRun=function(){return(c._OrtRun=c.asm.ia).apply(null,arguments)};c._OrtEndProfiling=function(){return(c._OrtEndProfiling=c.asm.ja).apply(null,arguments)};
c._JsepOutput=function(){return(c._JsepOutput=c.asm.ka).apply(null,arguments)};var Ha=c._malloc=function(){return(Ha=c._malloc=c.asm.la).apply(null,arguments)},jb=c._free=function(){return(jb=c._free=c.asm.ma).apply(null,arguments)};function mb(){return(mb=c.asm.oa).apply(null,arguments)}function nb(){return(nb=c.asm.pa).apply(null,arguments)}function ob(){return(ob=c.asm.qa).apply(null,arguments)}function hb(){return(hb=c.asm.sa).apply(null,arguments)}
function Ya(){return(Ya=c.asm.ta).apply(null,arguments)}function gb(){return(gb=c.asm.ua).apply(null,arguments)}function ib(){return(ib=c.asm.va).apply(null,arguments)}c.___start_em_js=888593;c.___stop_em_js=888754;c.stackAlloc=ob;c.stackSave=mb;c.stackRestore=nb;c.UTF8ToString=za;c.stringToUTF8=Ca;c.lengthBytesUTF8=Aa;var Z;S=function pb(){Z||qb();Z||(S=pb)};
function qb(){function a(){if(!Z&&(Z=!0,c.calledRun=!0,!K)){ta(ia);aa(c);if(c.onRuntimeInitialized)c.onRuntimeInitialized();if(c.postRun)for("function"==typeof c.postRun&&(c.postRun=[c.postRun]);c.postRun.length;){var b=c.postRun.shift();ja.unshift(b)}ta(ja)}}if(!(0<Q)){if(c.preRun)for("function"==typeof c.preRun&&(c.preRun=[c.preRun]);c.preRun.length;)ka();ta(ha);0<Q||(c.setStatus?(c.setStatus("Running..."),setTimeout(function(){setTimeout(function(){c.setStatus("")},1);a()},1)):a())}}
if(c.preInit)for("function"==typeof c.preInit&&(c.preInit=[c.preInit]);0<c.preInit.length;)c.preInit.pop()();qb();


  return ortWasm.ready
}

);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = ortWasm;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return ortWasm; });
else if (typeof exports === 'object')
  exports["ortWasm"] = ortWasm;
export default ortWasm;
